import {
  Client,
  ShootBooking,
  LedgerEntry,
  Invoice,
  KPISummary,
  Quotation,
  Enquiry,
} from '@/types';
import { defaultCatalog } from '@/lib/catalogDefaults';

export const mockClients: Client[] = [
  {
    id: 'cli-01',
    name: 'Alveera D’Souza & Jason Pinto',
    company: 'St. Aloysius Chapel & Summer Sands Ullal',
    brandTier: 'HAUTE_COUTURE',
    email: 'alveera.dsouza@gmail.com',
    city: 'Mangalore',
    totalBilled: 38000,
    totalPaid: 19000,
    status: 'ACTIVE',
  },
  {
    id: 'cli-02',
    name: 'Kavya Bhandary & Nithin Rai',
    company: 'TMA Pai International Convention Centre',
    brandTier: 'COMMERCIAL_LUXURY',
    email: 'nithin.rai@coastaltech.in',
    city: 'Mangalore',
    totalBilled: 42000,
    totalPaid: 21000,
    status: 'ACTIVE',
  },
  {
    id: 'cli-03',
    name: 'Zahid Mansoor Beary & Ayesha Fathima',
    company: 'The Ocean Pearl Grand Ballroom',
    brandTier: 'COMMERCIAL_LUXURY',
    email: 'zahid.beary@gmail.com',
    city: 'Mangalore',
    totalBilled: 34000,
    totalPaid: 17000,
    status: 'ACTIVE',
  },
  {
    id: 'cli-04',
    name: 'Neil Anthony Sequeira & Dr. Rhea D’Cunha',
    company: 'Milagres Church & Kadri Heritage Grounds',
    brandTier: 'PRIVATE_ESTATE',
    email: 'neil.sequeira@gmail.com',
    city: 'Mangalore',
    totalBilled: 29000,
    totalPaid: 14500,
    status: 'ACTIVE',
  },
  {
    id: 'cli-05',
    name: 'Prateek Shetty & Shwetha Hegde',
    company: 'Sasihithlu Coastal Estuary & Gold Finch',
    brandTier: 'EDITORIAL_PRESS',
    email: 'prateek.shetty@kudlacreative.in',
    city: 'Padubidri, Udupi',
    totalBilled: 39000,
    totalPaid: 19500,
    status: 'ACTIVE',
  },
];

export const mockShoots: ShootBooking[] = [
  {
    id: 'sht-sep-01',
    shootCode: 'LUM-TNB-26',
    title: 'Ananya & Gautham: Sunset Pre-Wedding Editorial & Coastal Stills',
    client: mockClients[0],
    type: 'Wedding Cinemastory & Stills',
    status: 'CONFIRMED',
    date: '2026-09-12',
    startTime: '15:30',
    endTime: '19:30',
    callTime: '14:30 (Sultan Battery Ferry Dock)',
    location: {
      name: 'Tannirbhavi Beach & Sultan Battery Estuary',
      city: 'Mangalore',
      coordinates: '12.8914° N, 74.8211° E',
      accessCode: 'TNB-COASTAL-09',
    },
    productionTeam: [
      { role: 'Lead Candid Photographer', name: 'Dan Aurel', initials: 'DA' },
      { role: 'Cinematographer (4K Motion)', name: 'Reuben Serrao', initials: 'RS' },
    ],
    shotListTotal: 22,
    shotListCompleted: 18,
    financialSummary: {
      totalFee: 24000,
      retainerPaid: 12000,
      balanceDue: 12000,
      currency: 'INR',
    },
    scheduleTimeline: [
      { time: '14:30', activity: 'Ferry crossing & equipment staging at Tannirbhavi pine grove', lead: 'Dan Aurel' },
      { time: '16:00', activity: 'Casual coastal editorial couple frames & golden glow stills', lead: 'Dan Aurel' },
      { time: '18:15', activity: 'Sunset 4K cinematic slow motion by crashing Arabian waves', lead: 'Reuben Serrao' },
    ],
    gearAllocated: [
      'Sony A7 IV + 35mm & 85mm GM Primes',
      'DJI Mini 4 Pro Aerial Drone',
      'Godox AD200 Pro with beauty dish',
    ],
    editorialNotes: 'Warm maritime tones. Golden hour backlight against Arabian sea breakers.',
    deliveryStage: 'EDITING_IN_PROGRESS',
    hardDriveReceived: true,
    clientSelectionDone: true,
  },
  {
    id: 'sht-sep-02',
    shootCode: 'LUM-JWL-26',
    title: 'Coastal Heritage Haute Jewelry: Autumn Editorial Lookbook',
    client: mockClients[4],
    type: 'High Jewelry Lookbook',
    status: 'CONFIRMED',
    date: '2026-09-20',
    startTime: '10:00',
    endTime: '18:00',
    callTime: '09:00 AM (Studio Stage A)',
    location: {
      name: 'Lumina Studio HQ & Kadri Heritage Villa',
      city: 'Kodialbail, Mangalore',
      coordinates: '12.8711° N, 74.8465° E',
      accessCode: 'LUM-STAGE-A',
    },
    productionTeam: [
      { role: 'Lead Candid Photographer', name: 'Dan Aurel', initials: 'DA' },
      { role: 'Lighting Director', name: 'Santhosh Bhandary', initials: 'SB' },
    ],
    shotListTotal: 30,
    shotListCompleted: 0,
    financialSummary: {
      totalFee: 36000,
      retainerPaid: 18000,
      balanceDue: 18000,
      currency: 'INR',
    },
    scheduleTimeline: [
      { time: '09:00', activity: 'Light tent calibration & macro focus rail rigging', lead: 'Santhosh Bhandary' },
      { time: '10:30', activity: 'Temple antique gold choker set macro captures with model', lead: 'Dan Aurel' },
      { time: '14:00', activity: 'Editorial styling against dark slate and warm ivory marble', lead: 'Dan Aurel' },
    ],
    gearAllocated: [
      'Sony A7R V + 90mm f/2.8 Macro GM',
      'Broncolor Siros 800 S Strobe System',
    ],
    editorialNotes: 'Pin-sharp diamond and ruby facet specular highlights. Zero chromatic aberration.',
    deliveryStage: 'SELECTION_PENDING',
    hardDriveReceived: true,
    clientSelectionDone: false,
  },
  {
    id: 'sht-01',
    shootCode: 'LUM-MNG-26',
    title: 'Alveera & Jason: Catholic Nuptials & Ullal Beach Sunset Celebration',
    client: mockClients[0],
    type: 'Wedding Cinemastory & Stills',
    status: 'CONFIRMED',
    date: '2026-11-20',
    startTime: '08:30',
    endTime: '22:00',
    callTime: '07:30 AM (Bride Dressing Call)',
    location: {
      name: 'St. Aloysius Chapel & Summer Sands Beach Resort',
      city: 'Mangalore & Ullal',
      coordinates: '12.8724° N, 74.8427° E',
      accessCode: 'ALOYSIUS-PERMIT-26',
    },
    productionTeam: [
      { role: 'Lead Candid Photographer', name: 'Dan Aurel', initials: 'DA' },
      { role: 'Traditional Photographer', name: 'Roshan D’Silva', initials: 'RD' },
      { role: 'Cinematographer (4K Motion)', name: 'Reuben Serrao', initials: 'RS' },
      { role: 'Traditional Videographer', name: 'Karthik Rao', initials: 'KR' },
      { role: 'Drone Pilot (Aerial Cinema)', name: 'Farooq Mansoor', initials: 'FM' },
      { role: 'Grip & Lighting Assistant', name: 'Santhosh Bhandary', initials: 'SB' },
    ],
    shotListTotal: 28,
    shotListCompleted: 0,
    financialSummary: {
      totalFee: 38000,
      retainerPaid: 19000,
      balanceDue: 19000,
      currency: 'INR',
    },
    scheduleTimeline: [
      { time: '07:30', activity: 'Bridal gown, heirloom veil & detail macro captures', lead: 'Dan Aurel' },
      { time: '09:30', activity: 'St. Aloysius Chapel Nuptials Mass & Vow exchange', lead: 'Dan Aurel' },
      { time: '11:45', activity: 'Family traditional portraits in chapel colonnade', lead: 'Roshan D’Silva' },
      { time: '16:00', activity: 'Summer Sands Ullal golden hour beach cinematic couple session', lead: 'Reuben Serrao' },
      { time: '18:30', activity: 'Grand reception entry, bridal waltz & toast speeches', lead: 'Dan Aurel' },
      { time: '21:30', activity: 'Wrap, dual NVMe backup ingest and client preview', lead: 'Farooq Mansoor' },
    ],
    gearAllocated: [
      'Sony FX3 + Sony A7R V Dual Rig',
      'Sony GM 24-70mm f/2.8 & 85mm f/1.4',
      'DJI Mini 4 Pro Drone + ND Polarizers',
      'Godox AD400 Pro Wireless Strobes with Octaboxes',
      'Sennheiser AVX Wireless Lavalier Microphone Pack',
    ],
    editorialNotes: 'Rich coastal warm tones. Ensure high fidelity audio of church choir vows and seaside evening ambient lighting.',
    quotationId: 'q-07',
    deliveryStage: 'SELECTION_PENDING',
    hardDriveReceived: true,
    clientSelectionDone: false,
  },
  {
    id: 'sht-02',
    shootCode: 'LUM-TMA-27',
    title: 'Kavya & Nithin: Traditional Bunt Muhurtham & Grand Reception',
    client: mockClients[1],
    type: 'Royal Coastal Wedding',
    status: 'CONFIRMED',
    date: '2026-12-14',
    startTime: '07:00',
    endTime: '22:30',
    callTime: '06:00 AM',
    location: {
      name: 'Dr. TMA Pai International Convention Centre',
      city: 'MG Road, Kodialbail, Mangalore',
      coordinates: '12.8761° N, 74.8439° E',
      accessCode: 'TMA-PAI-HALL-A',
    },
    productionTeam: [
      { role: 'Lead Candid Photographer', name: 'Dan Aurel', initials: 'DA' },
      { role: 'Traditional Photographer', name: 'Roshan D’Silva', initials: 'RD' },
      { role: 'Cinematographer (4K Motion)', name: 'Reuben Serrao', initials: 'RS' },
      { role: 'Traditional Videographer', name: 'Karthik Rao', initials: 'KR' },
      { role: 'Drone Pilot (Aerial Cinema)', name: 'Farooq Mansoor', initials: 'FM' },
      { role: 'Grip & Lighting Assistant', name: 'Santhosh Bhandary', initials: 'SB' },
    ],
    shotListTotal: 32,
    shotListCompleted: 0,
    financialSummary: {
      totalFee: 42000,
      retainerPaid: 21000,
      balanceDue: 21000,
      currency: 'INR',
    },
    scheduleTimeline: [
      { time: '06:00', activity: 'Grip setup, stage flood lighting check, battery docks ready', lead: 'Santhosh Bhandary' },
      { time: '07:00', activity: 'Bride Mangalore traditional Kasavu gold waistbelt & hair styling', lead: 'Dan Aurel' },
      { time: '09:00', activity: 'Muhurtham rituals, Kanyadaan & Akshathe ceremonies', lead: 'Roshan D’Silva' },
      { time: '13:00', activity: 'Buffet & traditional coastal feast crowd captures', lead: 'Karthik Rao' },
      { time: '17:30', activity: 'Evening reception stage, drone hall exterior & gala celebration', lead: 'Farooq Mansoor' },
    ],
    gearAllocated: [
      'Sony A7S III + Ronin RS3 Pro Gimbal',
      'Sony A7 IV + 70-200mm f/2.8 GM II',
      'Aputure 300d II Key Light + Light Dome III',
      'DJI Air 3 Cine Drone (DGCA Certified)',
    ],
    editorialNotes: 'Vibrant golden hour and heritage temple jewelry clarity. Preserve deep red and turmeric hues in S-Cinetone grade.',
    quotationId: 'q-08',
    deliveryStage: 'RAW_INGESTED',
    hardDriveReceived: true,
    clientSelectionDone: false,
  },
  {
    id: 'sht-03',
    shootCode: 'LUM-OCN-28',
    title: 'Zahid & Ayesha: Heritage Nikkah & Ocean Pearl Reception',
    client: mockClients[2],
    type: 'Heritage Nikkah & Banquet',
    status: 'CONFIRMED',
    date: '2026-10-18',
    startTime: '10:00',
    endTime: '21:00',
    callTime: '09:00 AM',
    location: {
      name: 'The Ocean Pearl Grand Ballroom',
      city: 'Navabharath Circle, Kodialbail, Mangalore',
      coordinates: '12.8711° N, 74.8465° E',
      accessCode: 'OCN-BALLROOM-02',
    },
    productionTeam: [
      { role: 'Lead Candid Photographer', name: 'Dan Aurel', initials: 'DA' },
      { role: 'Traditional Photographer', name: 'Roshan D’Silva', initials: 'RD' },
      { role: 'Cinematographer (4K Motion)', name: 'Reuben Serrao', initials: 'RS' },
    ],
    shotListTotal: 24,
    shotListCompleted: 0,
    financialSummary: {
      totalFee: 34000,
      retainerPaid: 17000,
      balanceDue: 17000,
      currency: 'INR',
    },
    scheduleTimeline: [
      { time: '09:00', activity: 'Ballroom ambient illumination & stage setup check', lead: 'Roshan D’Silva' },
      { time: '10:30', activity: 'Groom procession and vintage car arrival', lead: 'Dan Aurel' },
      { time: '11:45', activity: 'Nikkah ceremonial contract signing & qabuliyat', lead: 'Dan Aurel' },
      { time: '14:00', activity: 'Dawat-e-Walima feast candid captures', lead: 'Reuben Serrao' },
      { time: '17:00', activity: 'Couple ballroom editorial portraits & family stage photos', lead: 'Dan Aurel' },
    ],
    gearAllocated: [
      'Sony A7 IV + 50mm f/1.2 GM Prime',
      'Sony FX3 Cinema Rig + Atomos Ninja V+',
      'Nanlite Pavotube II 30X RGB Tubes for stage backfill',
    ],
    editorialNotes: 'Intimate portrait framing. Soft pastel tones with emphasis on ornate bridal zardozi embroidery.',
    quotationId: 'q-09',
    deliveryStage: 'EDITING_IN_PROGRESS',
    hardDriveReceived: true,
    clientSelectionDone: true,
  },
  {
    id: 'sht-04',
    shootCode: 'LUM-MLG-29',
    title: 'Neil & Rhea: Milagres Church Nuptials & Traditional Roce',
    client: mockClients[3],
    type: 'Catholic Roce & Nuptials',
    status: 'CONFIRMED',
    date: '2026-11-28',
    startTime: '15:00',
    endTime: '22:00',
    callTime: '14:00',
    location: {
      name: 'Milagres Church & Jubilee Hall',
      city: 'Hampankatta, Mangalore',
      coordinates: '12.8682° N, 74.8421° E',
      accessCode: 'MILAGRES-JUBILEE-01',
    },
    productionTeam: [
      { role: 'Lead Candid Photographer', name: 'Dan Aurel', initials: 'DA' },
      { role: 'Traditional Videographer', name: 'Karthik Rao', initials: 'KR' },
    ],
    shotListTotal: 20,
    shotListCompleted: 0,
    financialSummary: {
      totalFee: 29000,
      retainerPaid: 14500,
      balanceDue: 14500,
      currency: 'INR',
    },
    scheduleTimeline: [
      { time: '14:00', activity: 'Jubilee hall stage decoration & audio tap into church PA system', lead: 'Karthik Rao' },
      { time: '15:30', activity: 'Milagres church vows, ring ceremony and choir entrance', lead: 'Dan Aurel' },
      { time: '18:00', activity: 'Traditional Roce coconut milk blessing captures and brass band rhythm', lead: 'Dan Aurel' },
      { time: '20:30', activity: 'Baila dance floor candid energy and family felicitation', lead: 'Dan Aurel' },
    ],
    gearAllocated: [
      'Sony A7R V + 35mm f/1.4 GM',
      'Sony FX3 + 24-105mm f/4 G OSS',
      'Godox V1 Flash with Dome Diffusers',
    ],
    editorialNotes: 'High shutter speed for lively Roce and Baila dance action. Candid natural expressions prioritized.',
    deliveryStage: 'RAW_INGESTED',
    hardDriveReceived: true,
    clientSelectionDone: false,
  },
];

export const mockLedger: LedgerEntry[] = [
  {
    id: 'led-01',
    transactionRef: 'REC-2026-901',
    date: '2026-09-10',
    description: 'Kavya & Nithin — 50% Royal Coastal Package Advance',
    category: 'CLIENT_RECEIVABLE',
    type: 'INCOME',
    amount: 21000,
    counterparty: 'Nithin Rai (Coastal Tech)',
    relatedShootCode: 'LUM-TMA-27',
    status: 'CLEARED',
    paymentMethod: 'UPI / GPay Direct',
  },
  {
    id: 'led-02',
    transactionRef: 'EXP-2026-442',
    date: '2026-09-08',
    description: 'SanDisk Extreme Pro 2TB NVMe Dual SSDs for 4K Ingest Backup',
    category: 'GEAR_RENTAL',
    type: 'EXPENSE',
    amount: 6800,
    counterparty: 'Hampankatta IT Mall Mangalore',
    relatedShootCode: 'LUM-MNG-26',
    status: 'CLEARED',
    paymentMethod: 'Corporate HDFC Current A/C',
  },
  {
    id: 'led-03',
    transactionRef: 'REC-2026-898',
    date: '2026-09-05',
    description: 'Alveera D’Souza — St. Aloysius Wedding Retainer Advance',
    category: 'CLIENT_RECEIVABLE',
    type: 'INCOME',
    amount: 19000,
    counterparty: 'Alveera D’Souza',
    relatedShootCode: 'LUM-MNG-26',
    status: 'CLEARED',
    paymentMethod: 'NEFT / Axis Bank Mangalore',
  },
  {
    id: 'led-04',
    transactionRef: 'EXP-2026-440',
    date: '2026-09-04',
    description: 'Ullal & Someshwara Set Crew Batta, Coastal Transit & Vehicle Fuel',
    category: 'TALENT_PAYOUT',
    type: 'EXPENSE',
    amount: 4500,
    counterparty: 'Roshan D’Silva Crew Logistics',
    relatedShootCode: 'LUM-MNG-26',
    status: 'CLEARED',
    paymentMethod: 'UPI Direct',
  },
  {
    id: 'led-05',
    transactionRef: 'REC-2026-892',
    date: '2026-09-02',
    description: 'Zahid Mansoor Beary — Nikkah Package 50% Advance',
    category: 'CLIENT_RECEIVABLE',
    type: 'INCOME',
    amount: 17000,
    counterparty: 'Zahid Mansoor Beary',
    relatedShootCode: 'LUM-OCN-28',
    status: 'CLEARED',
    paymentMethod: 'IMPS Transfer',
  },
  {
    id: 'led-06',
    transactionRef: 'EXP-2026-438',
    date: '2026-08-28',
    description: 'Drone DGCA Flight Clearance & Summer Sands Coastal Filming Permit',
    category: 'LOCATION_PERMIT',
    type: 'EXPENSE',
    amount: 3200,
    counterparty: 'Dakshina Kannada District Administration',
    relatedShootCode: 'LUM-MNG-26',
    status: 'CLEARED',
    paymentMethod: 'Karnataka Seva Sindhu Portal',
  },
  {
    id: 'led-07',
    transactionRef: 'REC-2026-880',
    date: '2026-08-22',
    description: 'Neil Anthony Sequeira — Milagres Roce & Nuptials 50% Advance',
    category: 'CLIENT_RECEIVABLE',
    type: 'INCOME',
    amount: 14500,
    counterparty: 'Neil Anthony Sequeira',
    relatedShootCode: 'LUM-MLG-29',
    status: 'CLEARED',
    paymentMethod: 'UPI / Google Pay',
  },
  {
    id: 'led-08',
    transactionRef: 'EXP-2026-431',
    date: '2026-08-18',
    description: 'Sony FX3 & A7R V Sensor Wet Cleaning & Lens Calibration',
    category: 'STUDIO_OVERHEAD',
    type: 'EXPENSE',
    amount: 2800,
    counterparty: 'Pro Cine Labs Mangalore Service',
    status: 'CLEARED',
    paymentMethod: 'Debit Card',
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: 'inv-101',
    invoiceNumber: 'INV-2026-084',
    clientId: 'cli-01',
    clientName: 'Alveera D’Souza & Jason Pinto',
    brand: 'St. Aloysius Chapel & Summer Sands Ullal',
    issueDate: '2026-09-01',
    dueDate: '2026-11-20',
    items: [
      { id: 'i1', description: 'Lead Candid Photography & Traditional Stills (Full Day Coverage)', quantity: 1, unitPrice: 18000, total: 18000 },
      { id: 'i2', description: 'Cinematic 4K Highlight Film & Full Ceremony Documentation', quantity: 1, unitPrice: 12000, total: 12000 },
      { id: 'i3', description: 'Premium 35-40 Page Matte-Finish Hardbound Wedding Album', quantity: 1, unitPrice: 5000, total: 5000 },
      { id: 'i4', description: 'Drone Aerial Cinema & Sunset Ullal Beach Coverage', quantity: 1, unitPrice: 3000, total: 3000 },
    ],
    subtotal: 38000,
    productionFeeTax: 0,
    totalAmount: 38000,
    balanceDue: 19000,
    status: 'PARTIAL',
  },
  {
    id: 'inv-102',
    invoiceNumber: 'INV-2026-085',
    clientId: 'cli-02',
    clientName: 'Kavya Bhandary & Nithin Rai',
    brand: 'TMA Pai International Convention Centre',
    issueDate: '2026-09-04',
    dueDate: '2026-12-14',
    items: [
      { id: 'i5', description: 'Royal Coastal Wedding Coverage (Candid + Traditional Dual Team)', quantity: 1, unitPrice: 20000, total: 20000 },
      { id: 'i6', description: '4K Multi-Camera Cinematic Film + Teaser Reel (Instagram Edit)', quantity: 1, unitPrice: 13000, total: 13000 },
      { id: 'i7', description: 'Drone Aerial Hall & Muhurtham Coverage', quantity: 1, unitPrice: 4000, total: 4000 },
      { id: 'i8', description: 'Signature Couple Archival Frame & 40-Page Layflat Album', quantity: 1, unitPrice: 5000, total: 5000 },
    ],
    subtotal: 42000,
    productionFeeTax: 0,
    totalAmount: 42000,
    balanceDue: 21000,
    status: 'PARTIAL',
  },
  {
    id: 'inv-103',
    invoiceNumber: 'INV-2026-086',
    clientId: 'cli-03',
    clientName: 'Zahid Mansoor Beary & Ayesha Fathima',
    brand: 'The Ocean Pearl Grand Ballroom',
    issueDate: '2026-09-06',
    dueDate: '2026-10-18',
    items: [
      { id: 'i9', description: 'Heritage Nikkah Photography & Candid Couple Portraits', quantity: 1, unitPrice: 16000, total: 16000 },
      { id: 'i10', description: 'Cinematic Highlights & Full Reception Ceremony Video', quantity: 1, unitPrice: 12000, total: 12000 },
      { id: 'i11', description: 'High-Resolution Edited Digital Plates & Master Archival Delivery', quantity: 1, unitPrice: 6000, total: 6000 },
    ],
    subtotal: 34000,
    productionFeeTax: 0,
    totalAmount: 34000,
    balanceDue: 17000,
    status: 'PARTIAL',
  },
  {
    id: 'inv-104',
    invoiceNumber: 'INV-2026-087',
    clientId: 'cli-04',
    clientName: 'Neil Anthony Sequeira & Dr. Rhea D’Cunha',
    brand: 'Milagres Church & Kadri Heritage Grounds',
    issueDate: '2026-09-08',
    dueDate: '2026-11-28',
    items: [
      { id: 'i12', description: 'Church Nuptials & Traditional Roce Ceremony Candid Coverage', quantity: 1, unitPrice: 16000, total: 16000 },
      { id: 'i13', description: 'Full-Length Video Coverage & Baila Celebration Highlights', quantity: 1, unitPrice: 9000, total: 9000 },
      { id: 'i14', description: 'Handcrafted Hardcover Photo Album (35 Pages)', quantity: 1, unitPrice: 4000, total: 4000 },
    ],
    subtotal: 29000,
    productionFeeTax: 0,
    totalAmount: 29000,
    balanceDue: 14500,
    status: 'PARTIAL',
  },
];

export const mockKPISummary: KPISummary = {
  netMargins: {
    amount: 54200,
    percentage: 75.8,
    changePct: 12.4,
  },
  cashFlow: {
    current: 71500,
    monthInflow: 71500,
    monthOutflow: 17300,
  },
  confirmedShoots: {
    count: 4,
    activeProductionDays: 5,
  },
  unpaidRetainers: {
    total: 71500,
    count: 4,
  },
};

export const mockQuotations: Quotation[] = [
  {
    id: 'q-07',
    quotationNumber: 'Q NO. 07',
    date: '6 August , 2026',
    clientName: 'Alveera D’souza',
    clientCity: 'Mangalore',
    clientPhone: '+91 98450 12849',
    clientEmail: 'alveera.dsouza@gmail.com',
    packageTitle: 'ST. ALOYSIUS WEDDING PACKAGE',
    requirements: [
      { id: 'req-01', name: 'Traditional Photography', price: '-', included: true },
      { id: 'req-02', name: 'Candid Photography', price: '-', included: true },
      { id: 'req-03', name: 'Cinematic Highlights', price: '-', included: true },
      { id: 'req-04', name: 'Traditional Videography', price: '-', included: true },
    ],
    deliverables: [
      { id: 'del-01', item: 'Edited High-Resolution Photos', details: '*varies per event generally 500 - 800', included: true },
      { id: 'del-02', item: 'Cinematic Highlight Video', details: '*duration 2-8 mintues', included: true },
      { id: 'del-03', item: 'Full-Length Edited Video', details: '*covers the whole event', included: true },
      { id: 'del-04', item: 'Premium Glossy & MATT Photo Album', details: '*35-40 pages', included: true },
      { id: 'del-05', item: 'Complimentary : Couple photo frame', details: '*archival gallery frame included', included: true },
    ],
    crewAllocation: [
      { id: 'crw-01', role: 'Lead Candid Photographer', number: 1, assignedTo: 'Dan Aurel' },
      { id: 'crw-02', role: 'Traditional Photographer', number: 1, assignedTo: 'Roshan D’Silva' },
      { id: 'crw-03', role: 'Cinematographer (4K Motion)', number: 1, assignedTo: 'Reuben Serrao' },
      { id: 'crw-04', role: 'Traditional Videographer', number: 1, assignedTo: 'Karthik Rao' },
    ],
    termsAndConditions: defaultCatalog.standardTerms,
    totalPrice: 38000, // Strictly below 45000
    advancePercentage: 50,
    status: 'SENT',
    enquiryId: 'enq-101',
    contactPerson: 'DAN AUREL',
    contactPhone: '+91 9380057445',
  },
  {
    id: 'q-08',
    quotationNumber: 'Q NO. 08',
    date: '18 August , 2026',
    clientName: 'Kavya Bhandary & Nithin Rai',
    clientCity: 'Padubidri, Udupi',
    clientPhone: '+91 99001 84720',
    clientEmail: 'nithin.rai@coastaltech.in',
    packageTitle: 'ROYAL COASTAL PACKAGE (TMA PAI)',
    requirements: [
      { id: 'req-01', name: 'Traditional Photography', price: '-', included: true },
      { id: 'req-02', name: 'Candid Photography', price: '-', included: true },
      { id: 'req-03', name: 'Cinematic Highlights', price: '-', included: true },
      { id: 'req-04', name: 'Traditional Videography', price: '-', included: true },
      { id: 'req-05', name: 'Drone Aerial Cinema Coverage', price: 'Included', included: true },
    ],
    deliverables: [
      { id: 'del-01', item: 'Edited High-Resolution Photos', details: '*varies per event generally 600 - 900', included: true },
      { id: 'del-02', item: 'Cinematic Highlight Video', details: '*duration 3-5 mintues with 4K color grade', included: true },
      { id: 'del-03', item: 'Full-Length Edited Video', details: '*covers the whole event in 4K UHD', included: true },
      { id: 'del-04', item: 'Premium Glossy & MATT Photo Album', details: '*35-40 pages', included: true },
      { id: 'del-05', item: 'Complimentary : Couple photo frame', details: '*archival frame included', included: true },
    ],
    crewAllocation: [
      { id: 'crw-01', role: 'Lead Candid Photographer', number: 1, assignedTo: 'Dan Aurel' },
      { id: 'crw-02', role: 'Traditional Photographer', number: 1, assignedTo: 'Roshan D’Silva' },
      { id: 'crw-03', role: 'Cinematographer (4K Motion)', number: 1, assignedTo: 'Reuben Serrao' },
      { id: 'crw-05', role: 'Drone Pilot (Aerial Cinema)', number: 1, assignedTo: 'Farooq Mansoor' },
      { id: 'crw-07', role: 'Grip & Lighting Assistant', number: 1, assignedTo: 'Santhosh Bhandary' },
    ],
    termsAndConditions: defaultCatalog.standardTerms,
    totalPrice: 42000, // Strictly below 45000
    advancePercentage: 50,
    status: 'ACCEPTED',
    enquiryId: 'enq-102',
    contactPerson: 'DAN AUREL',
    contactPhone: '+91 9380057445',
  },
  {
    id: 'q-09',
    quotationNumber: 'Q NO. 09',
    date: '28 August , 2026',
    clientName: 'Zahid Mansoor Beary',
    clientCity: 'Hampankatta, Mangalore',
    clientPhone: '+91 97412 55901',
    clientEmail: 'zahid.beary@gmail.com',
    packageTitle: 'HERITAGE NIKKAH PACKAGE (OCEAN PEARL)',
    requirements: [
      { id: 'req-01', name: 'Traditional Photography', price: '-', included: true },
      { id: 'req-02', name: 'Candid Photography', price: '-', included: true },
      { id: 'req-03', name: 'Cinematic Highlights', price: '-', included: true },
      { id: 'req-04', name: 'Traditional Videography', price: '-', included: true },
    ],
    deliverables: [
      { id: 'del-01', item: 'Edited High-Resolution Photos', details: '*varies per event generally 500 - 800', included: true },
      { id: 'del-02', item: 'Cinematic Highlight Video', details: '*duration 2-8 mintues', included: true },
      { id: 'del-03', item: 'Full-Length Edited Video', details: '*covers the whole event', included: true },
      { id: 'del-04', item: 'Premium Glossy & MATT Photo Album', details: '*35-40 pages', included: true },
      { id: 'del-05', item: 'Complimentary : Couple photo frame', details: '*archival gallery frame included', included: true },
    ],
    crewAllocation: [
      { id: 'crw-01', role: 'Lead Candid Photographer', number: 1, assignedTo: 'Dan Aurel' },
      { id: 'crw-02', role: 'Traditional Photographer', number: 1, assignedTo: 'Roshan D’Silva' },
      { id: 'crw-03', role: 'Cinematographer (4K Motion)', number: 1, assignedTo: 'Reuben Serrao' },
    ],
    termsAndConditions: defaultCatalog.standardTerms,
    totalPrice: 34000, // Strictly below 45000
    advancePercentage: 50,
    status: 'CONVERTED',
    enquiryId: 'enq-103',
    contactPerson: 'DAN AUREL',
    contactPhone: '+91 9380057445',
  },
  {
    id: 'q-10',
    quotationNumber: 'Q NO. 10',
    date: '4 September , 2026',
    clientName: 'Neil Anthony Sequeira',
    clientCity: 'Kadri, Mangalore',
    clientPhone: '+91 98860 33412',
    clientEmail: 'neil.sequeira@gmail.com',
    packageTitle: 'MILAGRES CHURCH NUPTIALS & ROCE',
    requirements: [
      { id: 'req-01', name: 'Traditional Photography', price: '-', included: true },
      { id: 'req-02', name: 'Candid Photography', price: '-', included: true },
      { id: 'req-03', name: 'Traditional Videography', price: '-', included: true },
    ],
    deliverables: [
      { id: 'del-01', item: 'Edited High-Resolution Photos', details: '*varies per event generally 400 - 600', included: true },
      { id: 'del-02', item: 'Full-Length Edited Video', details: '*covers the whole event', included: true },
      { id: 'del-03', item: 'Premium Glossy & MATT Photo Album', details: '*30-35 pages', included: true },
      { id: 'del-04', item: 'Complimentary : Couple photo frame', details: '*archival gallery frame included', included: true },
    ],
    crewAllocation: [
      { id: 'crw-01', role: 'Lead Candid Photographer', number: 1, assignedTo: 'Dan Aurel' },
      { id: 'crw-04', role: 'Traditional Videographer', number: 1, assignedTo: 'Karthik Rao' },
    ],
    termsAndConditions: defaultCatalog.standardTerms,
    totalPrice: 29000, // Strictly below 45000
    advancePercentage: 50,
    status: 'SENT',
    enquiryId: 'enq-104',
    contactPerson: 'DAN AUREL',
    contactPhone: '+91 9380057445',
  },
];

export const mockEnquiries: Enquiry[] = [
  {
    id: 'enq-101',
    enquiryNumber: 'ENQ-2026-101',
    clientName: 'Alveera D’souza',
    phone: '+91 98450 12849',
    email: 'alveera.dsouza@gmail.com',
    city: 'Mangalore',
    eventDate: '2026-11-20',
    eventType: 'Catholic Nuptials & Ullal Beach Reception',
    estimatedBudget: 38000, // Below 45000
    status: 'QUOTED',
    quotationId: 'q-07',
    notes: 'Bride requested St. Aloysius chapel altar ceremony coverage and sunset beach portraits at Summer Sands.',
    createdAt: '2026-08-05',
  },
  {
    id: 'enq-102',
    enquiryNumber: 'ENQ-2026-102',
    clientName: 'Kavya Bhandary & Nithin Rai',
    phone: '+91 99001 84720',
    email: 'nithin.rai@coastaltech.in',
    city: 'Padubidri, Udupi',
    eventDate: '2026-12-14',
    eventType: 'Traditional Bunt Wedding & TMA Pai Grand Reception',
    estimatedBudget: 42000, // Below 45000
    status: 'QUOTED',
    quotationId: 'q-08',
    notes: 'Requires drone aerial coverage for TMA Pai Convention Centre and 4K cinema highlight teaser reel.',
    createdAt: '2026-08-16',
  },
  {
    id: 'enq-103',
    enquiryNumber: 'ENQ-2026-103',
    clientName: 'Zahid Mansoor Beary',
    phone: '+91 97412 55901',
    email: 'zahid.beary@gmail.com',
    city: 'Hampankatta, Mangalore',
    eventDate: '2026-10-18',
    eventType: 'Heritage Nikkah & Banquet at Ocean Pearl',
    estimatedBudget: 34000, // Below 45000
    status: 'CONVERTED',
    quotationId: 'q-09',
    notes: 'Converted to confirmed order. 50% advance received via IMPS.',
    createdAt: '2026-08-25',
  },
  {
    id: 'enq-104',
    enquiryNumber: 'ENQ-2026-104',
    clientName: 'Neil Anthony Sequeira & Dr. Rhea D’Cunha',
    phone: '+91 98860 33412',
    email: 'neil.sequeira@gmail.com',
    city: 'Kadri, Mangalore',
    eventDate: '2026-11-28',
    eventType: 'Milagres Church Nuptials & Traditional Roce',
    estimatedBudget: 29000, // Below 45000
    status: 'QUOTED',
    quotationId: 'q-10',
    notes: 'Looking for documentary candid photography and traditional Roce ceremony coverage.',
    createdAt: '2026-09-02',
  },
  {
    id: 'enq-105',
    enquiryNumber: 'ENQ-2026-105',
    clientName: 'Prateek Shetty & Shwetha Hegde',
    phone: '+91 97400 88219',
    email: 'prateek.shetty@kudlacreative.in',
    city: 'Padubidri, Udupi',
    eventDate: '2026-12-22',
    eventType: 'Kadri Temple Muhurtham & Gold Finch Reception',
    estimatedBudget: 39000, // Below 45000
    status: 'NEW',
    notes: 'Pre-wedding sunset session requested at Sasihithlu beach estuary + morning temple rituals.',
    createdAt: '2026-09-11',
  },
];
